### Get all posts
GET http://127.0.0.1:8000/posts/posts/
Accept: application/json

### Get a single post
GET http://127.0.0.1:8000/posts/posts/1/
Accept: application/json

### Create a new post
POST http://127.0.0.1:8000/posts/posts/
Content-Type: application/json

{
  "title": "Test Post",
  "content": "This is a test post content"
}

### Update a post
PUT http://127.0.0.1:8000/posts/posts/1/
Content-Type: application/json

{
  "title": "Updated Test Post",
  "content": "This is updated content for the test post"
}

### Delete a post
DELETE http://127.0.0.1:8000/posts/posts/1/
Accept: application/json
